name: portfolio
description: "Personal portfolio website"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  url_launcher: ^6.3.1
  smooth_page_indicator: ^1.2.0+3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/skills/
    - assets/images/platforms/
    - assets/images/social/
    - assets/images/portfolio_project/
    - assets/images/farmers_mart/
    - assets/images/expense_manager/
    - assets/images/bikers_hub/
    - assets/images/newsflash/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  web:
    generate: true
    image_path: "assets/images/app_logo.png"